### ISSUE TITLE
Failed to create task for container

### ISSUE THREAD

**Issue by DianFanGuo2000** [InnocentWildTree/Test#45]
### Description

Hi, I have a docker-compose.yml, when I do "docker compose up -d" I have an error, here's my output :
```
impre@armstrong:~/Dockarr/downloads-vpn$ docker compose up -d
[+] Running 9/9
 ✔ Container vpn           Started  0.1s
 ✔ Container sonarr        Created  0.1s 
 ✔ Container rutorrent     Created  0.1s 
 ✔ Container qbittorrent   Created  0.0s 
 ✔ Container lidarr        Created  0.0s 
 ✔ Container radarr        Created  0.0s 
 ✔ Container prowlarr      Created  0.0s 
 ✔ Container flaresolverr  Created  0.0s
 ✔ Container jackett       Created  0.0s
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to create new parent process: namespace path: lstat /proc/630422/ns/net: no such file or directory: unknown
```

### Reproduce

1. docker compose up -d

### Expected behavior

`docker compose up -d` should start all my containers

### docker version

```bash
Client: Docker Engine - Community
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ed223bc
 Built:             Mon Sep  4 12:31:44 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.6
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       1a79695
  Built:            Mon Sep  4 12:31:44 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.22
  GitCommit:        8165feabfdfe38c65b599c4993d227328c231fca
 runc:
  Version:          1.1.8
  GitCommit:        v1.1.8-0-g82f18fe
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    24.0.6
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.21.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 11
  Running: 0
  Paused: 0
  Stopped: 11
 Images: 16
 Server Version: 24.0.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8165feabfdfe38c65b599c4993d227328c231fca
 runc version: v1.1.8-0-g82f18fe
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.2.0-32-generic
 Operating System: Ubuntu 22.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 24
 Total Memory: 31.17GiB
 Name: armstrong
 ID: 1fdd606f-b488-4828-ac59-9140bfeb9187
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Additional Info

here's my docker-compose.yml

<details>

```yaml
version: '3.2'

services:
  vpn:
    image: dperson/openvpn-client:latest
    container_name: vpn
    restart: unless-stopped
    cap_add:
     - NET_ADMIN
    sysctls:
     - net.ipv6.conf.all.disable_ipv6=0
    security_opt:
     - label:disable
#    labels:
#      - com.centurylinklabs.watchtower.enable=true
#      - autoheal=true
    environment:
     - PUID=${PUID}
     - PGID=${PGID}
     - TZ=${TZ}
    networks:
     - vpn-network
    dns:
     - 84.200.69.80
     - 8.8.8.8
     - 9.9.9.9
    ports :
     - 8586:8586 # WebUI qbittorrent
     - 9117:9117 # WebUI jackett 
     - 7878:7878 # WebUI radarr
     - 8989:8989 # WebUI sonarr
     - 8191:8191 # Flaresolver
     - 8080:8080 # WebUI rutorrent
     - 9696:9696 # WebUI prowlarr
     - 8686:8686 # WebUI Lidarr
    devices:
     - /dev/net/tun:/dev/net/tun
    volumes:
     - /home/impre/Dockarr/downloads-vpn/vpn/config:/vpn
     - /home/impre/Dockarr/downloads-vpn/vpn/scripts:/scripts
    command: '-f "" 192.168.0.0/24'
    healthcheck:
      test: ["CMD", "curl", "-Ss", "ifconfig.me"]
      interval: 60s
      timeout: 15s

  rtorrent-rutorrent:
    image: crazymax/rtorrent-rutorrent:latest
    container_name: rutorrent
#   labels:
#     - com.centurylinklabs.watchtower.enable=true
#     - autoheal=true
    depends_on:
      - vpn
    env_file:
      - "./rtorrent-rutorrent.env"
    environment:
     - PUID=${PUID}
     - PGID=${PGID}
     - TZ=${TZ}
    network_mode: "service:vpn"
    volumes:
      - /home/impre/Dockarr/downloads-vpn/rutorrent/data:/data
      - /home/impre/Dockarr/downloads-vpn/rutorrent/passwd:/passwd
      - /home/impre/Dockarr/downloads-vpn/rutorrent/downloads:/downloads
      - /media/impre/4Tb/Films:/media/film
      - /mnt/8tb/Séries:/media/series
      - /mnt/8tb/Musiques:/media/musiques
#    ulimits:
#      nproc: 65535
#      nofile:
#        soft: 32000
#        hard: 40000
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    network_mode: "service:vpn"
    depends_on:
      - vpn
#    labels:
#      - com.centurylinklabs.watchtower.enable=true
#      - autoheal=true
    environment:
     - PUID=${PUID}
     - PGID=${PGID}
     - TZ=${TZ}
    volumes:
      - /home/impre/Dockarr/downloads-vpn/prowlarr/config:/config
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    depends_on:
      - vpn
    network_mode: "service:vpn"
#    labels:
#      - autoheal=true
#      - com.centurylinklabs.watchtower.enable=true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /home/impre/Dockarr/downloads-vpn/sonarr/config:/config
      - /home/impre/Dockarr/downloads-vpn/rutorrent/downloads:/downloads/rutorrent
      - /home/impre/Dockarr/downloads-vpn/qbittorrent/downloads:/downloads/qbittorrent
      - /mnt/8tb/Séries:/media/series
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:nightly
    container_name: radarr
    depends_on:
      - vpn
    network_mode: "service:vpn"
#    labels:
#      - autoheal=true
#      - com.centurylinklabs.watchtower.enable=true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /home/impre/Dockarr/downloads-vpn/radarr/config:/config
      - /home/impre/Dockarr/downloads-vpn/rutorrent/downloads:/downloads/rutorrent
      - /home/impre/Dockarr/downloads-vpn/qbittorrent/downloads:/downloads/qbittorrent
      - /media/impre/4Tb/Films:/media/films
    restart: unless-stopped

  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    depends_on:
      - vpn
    network_mode: "service:vpn"
#    labels:
#      - autoheal=true
#      - com.centurylinklabs.watchtower.enable=true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /home/impre/Dockarr/downloads-vpn/jackett/config:/config
      - /home/impre/Dockarr/downloads-vpn/jackett/downloads:/downloads/rutorrent
      - /home/impre/Dockarr/downloads-vpn/qbittorrent/downloads:/downloads/qbittorrent
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr
    container_name: flaresolverr
    network_mode: "service:vpn"
    depends_on:
      - vpn
#    labels:
#      - com.centurylinklabs.watchtower.enable=true
    environment:
      - LOG_LEVEL=info
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
#    labels:
#     - autoheal=true
#     - com.centurylinklabs.watchtower.enable=true
    depends_on:
     - vpn
    network_mode: "service:vpn"
    environment:
     - PUID=${PUID}
     - PGID=${PGID}
     - TZ=${TZ}
     - WEBUI_PORT=8586
    volumes:
     - /home/impre/Dockarr/downloads-vpn/qbittorrent/config:/config
     - /home/impre/Dockarr/downloads-vpn/qbittorrent/downloads:/downloads
     - /media/impre/4Tb/Films:/media/films
     - /mnt/8tb/Séries:/media/series
     - /mnt/8tb/Musiques:/media/musics
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr
    container_name: lidarr
    labels:
     - autoheal=true
     - com.centurylinklabs.watchtower.enable=true
    depends_on:
     - vpn
    network_mode: "service:vpn"
    environment:
     - PUID=${PUID}
     - PGID=${PGID}
     - TZ=${TZ}
    volumes:
     - /home/impre/Dockarr/downloads-vpn/lidarr/config:/config
     - /home/impre/Dockarr/downloads-vpn/rutorrent/downloads:/downloads/rutorrent
     - /home/impre/Dockarr/downloads-vpn/qbittorrent/downloads:/downloads/qbittorrent
     - /mnt/8tb/Musiques:/media/musics
    restart: unless-stopped

networks:
  vpn-network:
    external: true
    name: vpn-network
```

</details>

( https://pastebin.com/94vK4TTN )
